# Gather rpm package facts
- name: Gather rpm package facts
  package_facts:
    manager: auto
   
# Install Kibana 
- name: Install Kibana
  apt:
    name: kibana
    update_cache: yes
  when: "'kibana' not in ansible_facts.packages"

# Configure Kibana
- name: Update kibana server ip
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: {{ kibana_server_ip }}'

- name: Update kibana server port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: {{ kibana_server_port }}'

# Start Kibana
- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: Wait for kibana to become ready before adding dasboards
  pause:
      seconds: 35 
  when: kibana_extra_dashboards|length

- name: Import additional dashboards
  uri:
    url: http://{{ kibana_server_ip }}:{{ kibana_server_port }}/api/saved_objects/_import
    method: POST
    return_content: yes
    user: "kibana"
    password: "kibana"
    force_basic_auth: yes
    body:
      file:
        content: "{{ lookup('file', item) }}"
        filename: "{{ item | basename }}"
        mime_type: application/json
    body_format: form-multipart
    headers:
      kbn-xsrf: true
    loop: "{{ kibana_extra_dashboards }}"
    
