# Gather rpm package facts
- name: Gather rpm package facts
  package_facts:
    manager: auto

- name: Unhold kibana version for install
  command: apt-mark unhold kibana
  changed_when: false

# Install Kibana 
- name: Install Kibana
  apt:
    name: kibana{% if elastic_stack_version is defined and elastic_stack_version|length>0 %}={{ elastic_stack_version }}{% endif %}
    update_cache: yes
  when: "'kibana' not in ansible_facts.packages"

- name: Hold kibana version
  command: apt-mark hold kibana
  when: elastic_stack_version_lock
  changed_when: false


- name: Ensure certs directory exits
  file:
    path: "{{ kibana_ssl_certs_path }}"
    state: directory
    mode: "02750"
    owner: root
    group: kibana
  when:
    - kibana_xpack_security_enabled|bool
    - kibana_server_ssl_enabled|bool

- name: Copy kibana HTTP ssl certificates
  copy:
    src: "{{ item }}"
    dest: "{{ kibana_ssl_certs_path }}/{{ item | basename }}"
    mode: "0660"
    owner: root
    group: kibana
  loop:
    - "{{ kibana_server_ssl_cert }}"
    - "{{ kibana_server_ssl_key }}"
  when:
    - kibana_xpack_security_enabled|bool
    - kibana_server_ssl_enabled|bool
    - kibana_ssl_copy_certs|bool
  notify: restart kibana

- name: Configure kibana
  become: yes
  template:
    src: "{{ kibana_config_tpl }}"
    dest: "{{ kibana_config_dest }}"
    mode: "0660"
    owner: root
    group: kibana
  notify: restart kibana

# Start Kibana
- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: true

- name: Wait for kibana to become ready before adding dasboards
  pause:
      seconds: 35 
  when: kibana_extra_dashboards|length

- name: Import additional dashboards
  uri:
    url: "{{ kibana_server_protocol }}://{{ kibana_server_ip }}:{{ kibana_server_port }}/api/saved_objects/_import"
    method: POST
    return_content: yes
    user: "{{ kibana_xpack_username }}"
    password: "{{ kibana_xpack_password }}"
    force_basic_auth: yes
    body:
      file:
        content: "{{ lookup('file', item) }}"
        filename: "{{ item | basename }}"
        mime_type: application/json
    body_format: form-multipart
    headers:
      kbn-xsrf: true
  loop: "{{ kibana_extra_dashboards }}"
    
